version: "3.8"

services:
  db:
    image: mariadb:latest
    ports:
      - 7001:3306
    networks:
      - wordpress-dev-env
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 7000:80
    networks:
      - wordpress-dev-env
    volumes:
      - wp_data:/var/www/html/
      - ./wordpress_plugins:/var/www/html/wp-content/plugins/
      - ./wordpress_themes:/var/www/html/wp-content/themes/
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1

  wordpress-cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    user: xfs
    command: >
      /bin/sh -c '
      sleep 10;
      wp core install --path="/var/www/html" --url="http://localhost:7000" --title="Local Wordpress By Docker" --admin_user=admin --admin_password=admin --admin_email=foo@bar.com
      '
    networks:
      - wordpress-dev-env
    volumes:
      - wp_data:/var/www/html/

  adminer:
    depends_on:
      - db
    image: adminer:latest
    restart: always
    ports:
      - 7002:8080
    networks:
      - wordpress-dev-env

networks:
  wordpress-dev-env:

volumes:
  db_data:
  wp_data:
